
### GET global status
GET http://{{host}}:{{port}}/api/kestro/status

### GET projects
GET http://{{host}}:{{port}}/api/kestro/timeregistration/projects

### GET employees
GET http://{{host}}:{{port}}/api/kestro/timeregistration/employees


### GET registrations
GET http://{{host}}:{{port}}/api/kestro/timeregistration/registrations?date=2026-03-01